name: Upload Python Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      crawlabImageTag:
        description: 'crawlabteam/crawlab:<tag>'
        required: true
        default: 'latest'
        type: choice
        options:
          - latest
          - develop

env:
  PACKAGE_NAME: crawlab-demo

jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest
#    services:
#      master:
#        image: crawlabteam/crawlab:${{ inputs.crawlabImageTag || 'latest' }}
#        env:
#          CRAWLAB_NODE_MASTER: Y
#          CRAWLAB_MONGO_HOST: mongo
#        ports:
#          - "8080:8080"
#      mongo:
#        image: mongo:4.2

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt

#      - name: Unit Test
#        run: |
#          python -m unittest crawlab_demo.test

      - name: Check version
        run: |
          version=`python setup.py --version`
          echo "version: $version"
          res=`curl https://pypi.org/project/${{ env.PACKAGE_NAME }}/${version}/ -i -s | head -n 1`
          if [[ $res =~ 404 ]]; then
            echo "is_matched=1" >> $GITHUB_ENV 
          else
            :
          fi

      - name: Build and publish
        if: ${{ env.is_matched == '1' }}
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          pip install twine
          twine upload dist/*

      - name: Trigger other workflows
        if: ${{ env.is_matched == '1' }}
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.WORKFLOW_ACCESS_TOKEN }}
          repository: crawlab-team/docker-base-images
          event-type: crawlab-base