name: Upload Python Package

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      master:
        image: crawlabteam/crawlab
        env:
          CRAWLAB_NODE_MASTER: Y
          CRAWLAB_MONGO_HOST: mongo
        ports:
          - "8080:8080"
      mongo:
        image: mongo:4.2
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          pip install -r requirements.txt

      - name: Test
        run: |
          python -m unittest crawlab_demo.test
          crawlab-cli login -a http://localhost:8080/api -u admin -p admin

      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          pip install twine
          twine upload dist/*